# Generated by Django 2.1 on 2018-08-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20180826_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='user',
        ),
        migrations.AddField(
            model_name='travel',
            name='user',
            field=models.ManyToManyField(related_name='my_trips', to='trip.User'),
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
