# Generated by Django 2.1 on 2018-08-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='postedByID',
            new_name='posted_by',
        ),
    ]
