# Generated by Django 2.1 on 2018-08-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='dtart_date',
            new_name='start_date',
        ),
    ]
